### PR TITLE
더 많은 아이템을 리스트업 하였습니다

### PR DESCRIPTION
**Pull request by deep-diver**
대체로 fastai 사용을 위한 다양한 환경에 대한 설정/사용법에 대한 글 (공식 웹페이지에서 참조)
+ 더불어, 카테고리가 많아지는 관계로, 초반부에 각 카테고리로 이동하기 위한 링크를 별도로 뽑아두었습니다.

### CODE REVIEW

**Comment by kkweon** [comment]
Minor nitpick. But not sure if it would do as intended so I wrote reasons why I think it is.


Before:
```
## fast.ai 코스 강의노트
<a name="fastai-course-note"></a>
```

After:
```
<div id="fastai-course-note"></div>
## fast.ai 코스 강의노트
```

Reason:

1. Jump to before the section so the header is visible.
1. anchor tag is not necessary. general div tag
1. id over name is preferred.

**Comment by deep-diver** [comment]
@kkweon 
I just grabbed a code snippet from other repo, so I didn't know using <div> over <a> for referring the section on the same page is preferred.

I just replaced all the <a> tags with your suggestion, except with an additional space between <div> tag and ## heading. ## syntax didn't work with a HTML tag right above.

```
<div id="fastai-course-note"></div>

## fast.ai 코스 강의노트
```

**Comment by kkweon** [comment]
That's why people need code reviews :D

**Comment by kkweon** [comment]
Just FYI.

After playing a few times,
I believe the most web-way of doing this is to use `<span id="..."></span>` in the same line as the header text. Then, clicking the link in TOC will lead to the header right on, which is the most natural behavior.


```markdown
### TOC
- [Korean Header](#header)

### Korean Header lorem ipsum <span id="header"></span>

Content Content
```

**Comment by deep-diver** [comment]
@kkweon Thanks! It's very helpful information :)

**Pull request merged**
